app = 'plexio'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  CACHE_TYPE = 'memory'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[mounts]]
  source = 'plexio_data'
  destination = '/data'
