[project]
name = "plexio"
readme = "README.md"
requires-python = ">=3.11"
dynamic = ["version"]
dependencies = [
    "fastapi==0.141.1",
    "pydantic-settings==2.15.0",
    "yarl==1.24.5",
    "uvicorn==0.52.1",
    "aiohttp==3.14.3",
    "redis==8.1.0",
    "sentry-sdk[fastapi]==2.66.1",
    "aiosqlite==0.22.1",
    "cryptography==50.0.0"
]

[project.optional-dependencies]
dev = [
    "pip-audit==2.9.0",
    "ruff==0.16.2"
]

[tool.hatch.version]
path = "plexio/__init__.py"

[tool.setuptools]
packages = ["plexio"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "C",   # flake8-comprehensions
    "B",   # flake8-bugbear
]

[tool.ruff.lint.isort]
split-on-trailing-comma = true
force-wrap-aliases = true
combine-as-imports = true

[tool.ruff.format]
quote-style="single"
